name: CarltonFC
favicon: null
layout_spectrum: 0.46521
typography_spectrum: 0.15606572339311242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01172c'
    - '#3e5364'
    - '#c5d8e9'
    - '#90a3b2'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
